name: Publish on new changes

on:
  push:
    branches:
      - feature/new-structure

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
