name: Publish nugets on new changes

on:
  push:
    branches: 
      - main
  pull_request:
    branches: main
    types:
      - closed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NUGET_VERSION: 0.1.${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack -c Release --no-build -p:VersionPrefix=${{ env.NUGET_VERSION }}
    - name: Publish
      run: find . -iname "*.${{ env.NUGET_VERSION }}.nupkg" -print0 | xargs -r -0 dotnet nuget push *.${{ env.NUGET_VERSION }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
